// apps/shell-vue/src/App.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { RouterLink, useRoute, useRouter } from "vue-router";
import { RemoteAppBoundary } from "@federlet/vue-shell";
import type { RemoteRouteConfig } from "@federlet/shared-types";
import { remoteRoutes } from "./remote-routes";
import { loadRuntimeRemoteRoutes } from "./runtime-manifest";

const route = useRoute();
const router = useRouter();
const routes = ref<RemoteRouteConfig[]>(remoteRoutes);
const routesReady = ref(false);

const currentRemoteRoute = computed(() =>
  routesReady.value
    ? routes.value.find((remoteRoute) =>
        route.path === remoteRoute.basename ||
        route.path.startsWith(`${remoteRoute.basename}/`),
      )
    : undefined,
);

const isHome = computed(() => route.path === "/");
const shouldShowRouteLoading = computed(
  () => !routesReady.value && !isHome.value,
);

onMounted(async () => {
  const runtimeRoutes = await loadRuntimeRemoteRoutes({
    fallbackRoutes: remoteRoutes,
  });
  routes.value = runtimeRoutes;
  routesReady.value = true;

  if (!isHome.value && !currentRemoteRoute.value) {
    await router.replace("/");
  }
});
</script>

<template>
  <div class="shell">
    <aside class="shell__sidebar">
      <RouterLink to="/" class="shell__brand">Federlet Vue</RouterLink>
      <nav>
        <RouterLink
          v-for="remoteRoute in routes"
          :key="remoteRoute.id"
          :to="remoteRoute.basename"
          class="shell__nav-link"
          active-class="shell__nav-link--active"
        >
          {{ remoteRoute.title }}
        </RouterLink>
      </nav>
    </aside>

    <main v-if="isHome" class="home">
      <p class="eyebrow">Rspack Module Federation</p>
      <h1>Vue Shell for mixed-framework remotes</h1>
      <p>
        The shell owns global layout and routing while each remote exposes a
        framework-neutral mount lifecycle.
      </p>

      <div class="remote-grid">
        <RouterLink
          v-for="remoteRoute in routes"
          :key="remoteRoute.id"
          :to="remoteRoute.basename"
          class="remote-card"
        >
          <span>{{ remoteRoute.title }}</span>
          <strong>{{ remoteRoute.remoteName }}</strong>
        </RouterLink>
      </div>
    </main>

    <main v-else-if="shouldShowRouteLoading" class="home">
      Loading remote routes...
    </main>

    <RemoteAppBoundary
      v-else-if="currentRemoteRoute"
      :key="currentRemoteRoute.id"
      :route="currentRemoteRoute"
    />
  </div>
</template>

// apps/shell-react/src/App.tsx
import { useEffect, useState } from "react";
import { Link, NavLink, Navigate, Route, Routes } from "react-router-dom";
import { RemoteAppBoundary } from "@federlet/react-shell";
import type { RemoteRouteConfig } from "@federlet/shared-types";
import { remoteRoutes } from "./remote-routes";
import { loadRuntimeRemoteRoutes } from "./runtime-manifest";

/**
 * Shell 首页，展示当前已登记的 remote 入口。
 */
function HomePage({ routes }: { routes: RemoteRouteConfig[] }) {
  return (
    <main className="home">
      <p className="eyebrow">Rspack Module Federation</p>
      <h1>React Shell for mixed-framework remotes</h1>
      <p>
        The shell owns global layout and routing while each remote exposes a
        framework-neutral mount lifecycle.
      </p>

      <div className="remote-grid">
        {routes.map((route) => (
          <Link key={route.id} to={route.basename} className="remote-card">
            <span>{route.title}</span>
            <strong>{route.remoteName}</strong>
          </Link>
        ))}
      </div>
    </main>
  );
}

/**
 * 创建远程路由元素
 * @param route 远程路由配置
 * @returns 远程路由元素
 */
export function createRemoteRouteElement(route: RemoteRouteConfig) {
  return <RemoteAppBoundary key={route.id} route={route} />;
}

/**
 * Shell 根组件。
 *
 * 负责全局布局、导航高亮和把 remote 路由交给 `RemoteAppBoundary` 挂载。
 */
export function App() {
  const [routes, setRoutes] = useState<RemoteRouteConfig[]>(remoteRoutes);
  const [routesReady, setRoutesReady] = useState(false);
  const remoteRouteElements = routesReady ? routes : [];

  useEffect(() => {
    let cancelled = false;

    void loadRuntimeRemoteRoutes({ fallbackRoutes: remoteRoutes }).then(
      (runtimeRoutes) => {
        if (!cancelled) {
          setRoutes(runtimeRoutes);
          setRoutesReady(true);
        }
      },
    );

    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <div className="shell">
      <aside className="shell__sidebar">
        <Link to="/" className="shell__brand">
          Federlet
        </Link>
        <nav>
          {routes.map((route) => (
            <NavLink
              key={route.id}
              to={route.basename}
              className={({ isActive }) =>
                isActive
                  ? "shell__nav-link shell__nav-link--active"
                  : "shell__nav-link"
              }
            >
              {route.title}
            </NavLink>
          ))}
        </nav>
      </aside>

      <Routes>
        <Route path="/" element={<HomePage routes={routes} />} />
        {remoteRouteElements.map((route) => (
          <Route
            key={route.id}
            path={route.path}
            element={createRemoteRouteElement(route)}
          />
        ))}
        <Route
          path="*"
          element={
            routesReady ? (
              <Navigate to="/" replace />
            ) : (
              <main className="home">Loading remote routes...</main>
            )
          }
        />
      </Routes>
    </div>
  );
}
